# precommit-shared/.pre-commit-hooks.yaml

# --- Hygiene (uses PyPI inside pre-commit's venv, so no system deps) ---
- id: org-detect-aws-credentials
  name: detect-aws-credentials (org)
  language: script
  entry: hooks/org_detect_aws_credentials.sh
  pass_filenames: true
  description: >
    Detects accidentally committed AWS credentials, excluding .feature files and test folders.


- id: org-detect-private-key
  name: detect-private-key (org)
  language: script
  entry: hooks/org_detect_private_key.sh
  pass_filenames: true

- id: org-check-merge-conflict
  name: check-merge-conflict (org)
  language: script
  entry: hooks/org_check_merge_conflict.sh
  pass_filenames: true

- id: org-end-of-file-fixer
  name: end-of-file-fixer (org)
  language: script
  entry: hooks/org_end_of_file_fixer.sh
  pass_filenames: true

- id: org-trailing-whitespace
  name: trailing-whitespace (org)
  language: script
  entry: hooks/org_trailing_whitespace.sh
  pass_filenames: true

- id: org-mixed-line-ending
  name: mixed-line-ending (org)
  language: script
  entry: hooks/org_mixed_line_ending.sh
  args: ["--fix=lf"]
  pass_filenames: true

- id: org-check-added-large-files
  name: check-added-large-files (org)
  language: script
  entry: hooks/org_check_added_large_files.sh
  args: ["--maxkb=1024"]
  pass_filenames: true


# --- Secrets (no global install; pinned) ---
- id: org-detect-secrets
  name: detect-secrets (org)
  language: script
  entry: hooks/org_detect_secrets.sh
  pass_filenames: true
  description: >
    Runs detect-secrets with org-wide exclusions (terraform, tools, build, test, etc.)

# --- Commit message lint (node env auto-managed by pre-commit) ---
- id: org-commitlint
  name: commitlint (org)
  language: script
  entry: hooks/org_commitlint.sh
  stages: [commit-msg]

# --- Prettier (XML plugin) ---
- id: org-prettier
  name: prettier (org)
  language: script
  entry: hooks/org_prettier.sh
  files: '(\.json$|\.ya?ml$|\.md$|\.css$|\.html$|\.xml$)'
  exclude: '(\.xhtml$|(^|.*/)(test|tests|__tests__|src/test)/)'

# --- Java format (self-bootstrapping JAR, no repo deps) ---
- id: org-google-java-format
  name: google-java-format (org)
  language: script
  files: \.java$
  entry: hooks/org_google_java_format.sh

# --- Checkstyle (self-bootstrapping JAR & config) ---
- id: org-checkstyle
  name: checkstyle (org)
  language: script
  files: \.java$
  entry: hooks/org_checkstyle.sh
  pass_filenames: true

# --- Gradle smart checks (changed projects only) ---
- id: org-gradle-compile-changed
  name: gradle compile (changed projects)
  language: script
  pass_filenames: false
  stages: [push]
  entry: hooks/org_gradle_compile_changed.sh

- id: org-gradle-static-changed
  name: gradle static analysis (changed projects)
  language: script
  pass_filenames: false
  stages: [push]
  entry: hooks/org_gradle_static_changed.sh

- id: org-pii
  name: semgrep (org PII)
  language: script
  entry: hooks/org_semgrep_pii.sh
  pass_filenames: true
  description: >
    Scans staged files for PII using org-curated Semgrep rules, with centralized exclusions.
